# PyTorch: Zero to GANs Assignment 1 :

### Introduciton to PyTorch

PyTorch is an open source machine learning library based on the Torch library, used for applications such as computer vision and natural language processing, primarily developed by Facebook's AI Research lab. It is free and open-source software released under the Modified BSD license


- torch.tensor
- torch.sigmoid
- torch.sin
- torch.take
- function 5

In [2]:
# Import torch and other required modules
import torch


## Function 1 - torch.tensor

It returns A torch.Tensor a multi-dimensional matrix containing elements of a single data type.


In [23]:
# Example 1 
w =  torch.randn(10)
x = torch.randn(10)
b = torch.rand(1)
print(w)
print(x)
print(b)


tensor([ 0.2459, -1.0071, -1.1244, -0.0366, -0.0963, -0.9494, -1.6529,  0.5823,
         0.0955, -0.8701])
tensor([ 0.5092,  0.3329,  0.2343,  1.1377, -0.3812, -1.5353, -1.8214,  0.4423,
        -2.1755,  0.4400])
tensor([0.0286])


 Here I use torch.randn which creates the tensor of the given lengths

In [29]:
# Example 2 - 

torch.tensor([[1., -1.,45,45,23,234,425], [1., -1.,423235,4232325,223233,23124,42235]])



tensor([[ 1.0000e+00, -1.0000e+00,  4.5000e+01,  4.5000e+01,  2.3000e+01,
          2.3400e+02,  4.2500e+02],
        [ 1.0000e+00, -1.0000e+00,  4.2324e+05,  4.2323e+06,  2.2323e+05,
          2.3124e+04,  4.2235e+04]])

Creating the tensor using torch.tensor and it converts various datatype into single datatype.

In [33]:
# Example 3 - breaking (to illustrate when it breaks)
torch.tensor([[1, "sd",34], [True, 4, 5]])

TypeError: new(): invalid data type 'str'

The toruch.tensor only accepts intVal or double/float, bool val but not string. 

Most important function for creating tensor from list , container, or random data generation.

## Function 2 - torch.sigmoid

It returns the sigmoid neuron of given tensor, sigmoid neuron is a popular model of classification in Deep Learning.

In [12]:
# Example 1 
w =  torch.randn(10)
x = torch.randn(10)
b = torch.rand(1)
perceptron = x@w.t()+b        #perceptron model
print(perceptron)
print("Sigmoid for the given perceptron")
print(torch.sigmoid(perceptron))

tensor([-10.6587])
Sigmoid for the given perceptron
tensor([2.3495e-05])


Here I use some random data for weights, inputs and bias anf first calculate the perceptron and then pass this value to the sigmoid.

In [6]:
# Example 2 - 

percetron = torch.tensor([0.0])
print(torch.sigmoid(perceptron))


As we know the value of sigmoid is 1/2 (i.e 0.5) when `w*x+b` is zero.

In [35]:
# Example 3 - breaking (to illustrate when it breaks)
print(torch.sigmoid(torch.tensor([0])))

RuntimeError: "sigmoid_cpu" not implemented for 'Long'

Passing long value as a tensor in sigmoid gives us an error message `"sigmoid_cpu" not implemented for 'Long'`

Sigmoid function is widely use for traing the model and parameter, it is heavily used for DNN.

## Function 3 - torch.sin
Returns a new tensor with the sine of the elements of input.

In [41]:
# Example 1 - working

torch.sin(torch.tensor([90.0]))

tensor([0.8940])

it finds the sin of given tensor values

In [47]:
# Example 2 - working
torch.sin(torch.tensor([1.,0,-1]))*2*3.14/360


tensor([ 0.0147,  0.0000, -0.0147])

It converts the sin of 1,0,-1 and then find the perfect value.

In [58]:
# Example 3 - breaking (to illustrate when it breaks)
torch.sin(torch.tensor([[23.,2,1,1,2,2/0]]))


ZeroDivisionError: division by zero

Here if we pass the 0/1 = infinty in the sin function the error occurs

This function is more useful while handling trignometric values and the mathematical calculations. It is also useful while finding the angles b/w tensors.

## Function 4 - torch.take

It is function which extract the tensor from given tensor based on the indices provide.
It take ndim tensor as input and treated as 1 dimentional tensor while indexing.

In [ ]:
# Example 1 - working
src = torch.tensor([[4, 3, 5],[6, 7, 8]])
torch.take(src, torch.tensor([0, 2, 5]))

Explanation about example

In [12]:
# Example 2 - working

Explanation about example

In [13]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

## Function 5 - ???

Add some explanations

In [14]:
# Example 1 - working

Explanation about example

In [15]:
# Example 2 - working

Explanation about example

In [16]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [17]:
!pip install jovian --upgrade --quiet

In [18]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
